#!/usr/bin/env bash

tpm_dir="$HOME/.local/share/.tmux/plugins/tpm"
tpm_repo_url="https://github.com/tmux-plugins/tpm"
bin_path="$tpm_dir/tpm"

if [[ -d "$tpm_dir" ]]; then
  git -C "$tpm_dir" pull --ff-only
else
  git clone "$tpm_repo_url" "$tpm_dir"
fi

if ! [[ -x "$bin_path" ]]; then
  chmod +x "$bin_path"
fi
