#!/usr/bin/env bash

sudo ufw enable
elephant service enable

sudo systemctl enable \
  ufw.service \
  bluetooth.service \
  power-profiles-daemon.service \
  docker.service

systemctl --user enable \
  pipewire.service \
  pipewire-pulse.service \
  wireplumber.service \
  playerctld.service \
  waybar.service \
  hyprpaper.service \
  hypridle.service \
  hyprpolkitagent.service \
  hypridle.service \
  spotify.service \
  hyprpaper.service
