#!/usr/bin/env bash

# Text Editor
# NOTE: installing TS with mise because the version in
# arch packages is outdated
mise use --global tree-sitter@latest
mise use --global lua@5.1
mise use --global ruby@latest
mise use --global node@latest
mise use --global java@latest # openjdk

# Walker
mise use --global go@latest
