################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=desc:Samsung Display Corp. 0x414D,preferred,auto,auto
monitor=,preferred,auto-center-up,auto # On top of the laptop screen
